language: bash
services: docker

env:
  - VERSION=11 VARIANT=openjdk-jdk 
  - VERSION=11 VARIANT=oracle-jdk 
  - VERSION=8 VARIANT=oracle-serverjre 

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VERSION"
  - imageBase="alfresco-base-java:$VERSION"
  - imageSuffix="${VARIANT:+-$VARIANT}"

script:
  - |
    (
      set -Eeuo pipefail
      set -x
      travis_retry docker build -t "$imageBase-$imageSuffix" "$(echo $VARIANT| gtr '-' '/')"
    )

after_script:
  - docker images

# vim:set et ts=2 sw=2:
